# Generated by Django 5.0.4 on 2024-04-30 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAppApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
